spring.application.name=gestion
spring.application.version=v1.0.0
server.port=8080

# Connexion à MongoDB Atlas
spring.data.mongodb.uri=${MONGODB_URI}
#spring.data.mongodb.uri=mongodb+srv://adjacourandour4:ismabsences@ac-fecoorg.bsg1rmr.mongodb.net/mydb?tls=true&retryWrites=true&w=majority

# spring.data.mongodb.database=gestionAbsence

# (optionnel) nom de la base de données par défaut
# spring.data.mongodb.database=maBase

# Afficher les requêtes MongoDB dans la console (facultatif pour debug)
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# Swagger
springdoc.swagger-ui.path=/docs
springdoc.packagesToExclude=com.project.gestion.utils.exceptions

# Emplacement des fichiers statiques
spring.web.resources.static-locations=classpath:/static/

