GET http://localhost:8080/api/v1/article
# ###


###

POST http://localhost:8080/api/v1/categories
Accept: application/json
Content-Type: application/json

{
    "name": "nameslip",
    "code": "codeslip"
}

###
GET http://localhost:8080/api/v1/categories

###


###

DELETE  http://localhost:8080/api/v1/categories/12

###

PUT http://localhost:8080/api/v1/categories/1
Accept: application/json
Content-Type: application/json

{
    "name": "name100",
    "code": "code100"
}

###

GET http://localhost:8080/api/v1/categories/1
###


###

POST http://localhost:8080/api/v1/article
Accept: application/json
Content-Type: application/json

{
    "code": "ouzeon",
    "name": "ouzeon",
    "prix": 14.0,
    "qteStock": 5,
    "categorieId": 1
  }


###

PUT http://localhost:8080/api/v1/article/1
Accept: application/json
Content-Type: application/json

{
        "code": "normale",
        "name": "normal",
        "prix": 12.0,
        "qteStock": 5,
        "categorieId": 2
    
}
###

GET http://localhost:8080/api/v1/article/1

  
###

GET http://localhost:8080/api/v1/article/byCategorie/1



###

Get http://localhost:8080/api/v1/article/byCategorieName/Categorie 01

###

GET http://localhost:8080/api/v1/clients?page=1&size=5


###

GET http://localhost:8080/api/v1/clients/1


###

GET http://localhost:8080/api/v1/clients/2/commandes




###


###

POST http://localhost:8080/api/v1/clients/commandes
Accept: application/json
Content-Type: application/json

{
  "name": "Jean Dupont",
  "tel": "776404098",
  "pays": "France",
  "rue": "12 rue de la Paix",
  "ville": "Paris",
  "commandes": [
    {
      "dateCommande": "2022-06-15",
      "montant": 50.0,
      "pays": "France",
      "ville": "Lyon"
    },
    {
      "dateCommande": "2022-07-20",
      "montant": 200.0,
      "pays": "Belgique",
      "ville": "Bruxelles"
    }
  ]
}

###

